---
- name: ensure that vsftpd is installed
  yum: pkg=vsftpd state=installed
  when: ansible_distribution == 'CentOS'
  tags: install_vsftpd

- name: ensure vsftpd is service unit
  service:
    name: vsftpd
    state: started
    enabled: true
  tags: install_vsftpd

- name: Create directory for anon download only access
  file:
    path: "{{ download_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: configure vsftpd

- name: Create directory for anon upload  access
  file:
    path: "{{ upload_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  tags: configure vsftpd

- name: Create configuration for vsftpd from template
  template: src=templates/vsftpd.conf.j2 dest=/etc/vsftpd/vsftpd.conf owner=root group=root mode=0600
  notify: restart vsftpd
  tags: configure vsftpd

- name: enable port 20 and 21
  firewalld:
    zone: public
    port: 20-21/tcp
    permanent: true
    state: enabled
  notify: restart firewalld
  tags: configure_firewalld

- name: allow traffic in default zone for ftp service
  firewalld:
    zone: public
    service: ftp
    permanent: true
    state: enabled
  notify: restart firewalld
  tags: configure_firewalld

- name: install python libs for selinux
  yum: name="{{ item }}" state=installed
  loop: ['python3-libselinux', 'python3-libsemanage','policycoreutils-python-utils']
  when: ansible_distribution == 'CentOS'
  tags: configure_selinux

- name: readnwrite through upload dir and files
  sefcontext:
    target: '{{ upload_dir }}(/.*)?'
    setype: public_content_rw_t
    reload: True
    state: present
  register: filecontext1
  notify: restore context1

- name: readonly through dowload dir
  sefcontext:
    target: '{{ download_dir }}'
    setype: public_content_t
    reload: True
    state: present
  register: filecontext2
  notify: restore context2

- name : blahblahblah1
  debug:
    msg: "{{ filecontext1 }}"

- name: blahblahblah2
  debug:
    msg: "{{ filecontext2 }}"


#- name: read and write permissions through vsftpd
#  sefcontext:
#    target: '"{{ upload_dir }}"(/.*)?'
#    setype: public_content_rw_t
#    state: present

#- name: Apply context for download_dir
#  become: True
 # shell: restorecon -R -v "{{ download_dir }}"

#- name: Apply context for upload_dir
#  become: True
#  command: restorecon -R -v "{{ upload_dir }}"

- name: Set ftpd_anon_write flag on and keep it persistent
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes