---
- name: ensure  vsdtpd is installed
    yum: pkg=vsftpd state=installed
    when: ansible_distribution == 'CentOS'
    tags: install_vsftpd

- name: Create a for pub access
    path: /var/ftp/pub
    state: directory
    owner: root
    group: root
    mode: 0600
    tags: configure vsftpd

