---
  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: (httpd_exists.stdout == '1')

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted