---
  - name: restart vsftpd
    service:
      name: vsftpd
      state: restarted

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted

  - name: set context
    shell: restorecon -R -v {{ item }}
    with_items:
      - '{{ download_dir }}'
      - '{{ upload_dir }}'